version: '3.3'
services:
  application:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - './:/var/www/html/'
    networks:
     - demo-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - './:/var/www/html/'
      - './default.conf:/etc/nginx/conf.d/default.conf'
      - './log:/var/log/nginx/'
    ports:
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']
    networks:
      - demo-network

networks:
  demo-network:
    driver: bridge
